babylonlexer:
    hostname: babylonlexer-py3
    image: rbann/babylonlexer-py3
    command: shell
    volumes:
        - "../run.py:/opt/config/run.py"
        - "../..:/pygments-lexer-babylon"
    environment:
        PYTHONUNBUFFERED: 1
        PIP_COMMAND: pip3
        PYTHON_COMMAND: python3
        PYGMENTS_NODE_COMMAND: nodejs
