babylonlexer:
    hostname: babylonlexer-py2
    image: rbann/babylonlexer-py2
    command: shell
    volumes:
        - "../run.py:/opt/config/run.py"
        - "../..:/pygments-lexer-babylon"
    environment:
        PYTHONUNBUFFERED: 1
        PIP_COMMAND: pip
        PYTHON_COMMAND: python
        PYGMENTS_NODE_COMMAND: node
