babylonlexer:
    hostname: babylonlexer-node10
    image: rbann/babylonlexer-node10
    command: shell
    volumes:
        - "../run.py:/opt/config/run.py"
        - "../..:/pygments-lexer-babylon"
    environment:
        PYTHONUNBUFFERED: 1
        PIP_COMMAND: pip
        PYTHON_COMMAND: python
        PYGMENTS_NODE_COMMAND: blabla
