babylonlexer:
    hostname: babylonlexer
    image: rbann/babylonlexer-node10
    volumes:
        - "../run.py:/opt/config/run.py"
        - "../..:/pygments-lexer-babylon"
    environment:
        PYTHONUNBUFFERED: 1
